### ISSUE TITLE
Proxy Challenge.gov Pages through Rails app

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#30]
- [x] Set up the Rails application to load static pages hosted by the Pages build so that those pages remain accessible on Challenge.gov/resources etc
- [x] Proxy all URLs that are not / and /challenges or /challenge (this should be resources, user-guide, blog, terms, about, contact, privacy-policy)

**Comment by r-bartlett-gsa** [comment]
@danivovich and @stepchud A few questions:

- How these updates should be QA'ed?
- In the beginning of the project I believe we discussed that if we proxy pages through rails, then USWDS version on rails will apply to pages. Is that the case?

**Comment by danivovich** [comment]
@r-bartlett-gsa This can be QAed just by making sure the site behaves as it should while remaining on the domain name for the eval dev platform, and only directing into the portal when it normally would, and never redirecting to the cloud.gov pages preview urls. This does not change the USWDS version for the pages, it just passes them through so that its all under the single domain as the platform will be.
